"use client";

import { useEffect, useRef, useState } from "react";
import { HighlightedJson } from "@/lib/jsonHighlight";
import { needsJsonShapeGeneration } from "@/lib/jsonShapeAi";
import type { JsonShapeRef } from "@/lib/jsonShapes";
import { type useErd } from "./useErd";

type Erd = ReturnType<typeof useErd>;

export function JsonSchemaDrawer({
  erd,
  shape,
  onClose,
}: {
  erd: Erd;
  shape: JsonShapeRef;
  onClose: () => void;
}) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { tables, generateJsonShape } = erd;
  const table = tables.find((t) => t.id === shape.tableId);
  const column = table?.columns.find((c) => c.id === shape.columnId);
  const needsAi = !!column && needsJsonShapeGeneration(column);

  useEffect(() => {
    if (!needsAi) return;
    let cancelled = false;

    void (async () => {
      setGenerating(true);
      setError(null);
      try {
        await generateJsonShape(shape.tableId, shape.columnId);
      } catch (err) {
        if (!cancelled) {
          setError(
            err instanceof Error ? err.message : "Could not generate description."
          );
        }
      } finally {
        if (!cancelled) setGenerating(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [needsAi, shape.columnId, shape.tableId, generateJsonShape]);

  const liveShape =
    column && table
      ? {
          ...shape,
          description:
            column.json_description?.trim() ||
            (generating
              ? "Generating description with AI…"
              : "Description will be generated by AI."),
          jsonSchema: column.json_schema ?? shape.jsonSchema,
        }
      : shape;

  return (
    <aside className="flex h-full w-[420px] flex-none flex-col border-l border-[#1d2740] bg-[#0c111c]">
      <div className="flex h-12 flex-none items-center justify-between gap-3 border-b border-[#1d2740] px-4">
        <div className="flex min-w-0 items-center gap-2.5">
          <span className="flex-none font-mono text-[10px] text-accent-purple">
            7.{liveShape.index}
          </span>
          <span className="truncate font-mono text-[13px] font-semibold text-ink">
            {liveShape.label}
          </span>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close schema panel"
          className="flex h-7 w-7 flex-none cursor-pointer items-center justify-center rounded-md text-lg text-[#7e8aa6] transition-colors hover:bg-card hover:text-ink"
        >
          ×
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        <div className="mb-3.5 flex items-start justify-between gap-3">
          <p className="text-[12px] leading-relaxed text-[#9aa6c2]">
            {liveShape.description}
          </p>
          <button
            type="button"
            disabled={generating}
            onClick={() => {
              setGenerating(true);
              setError(null);
              void generateJsonShape(shape.tableId, shape.columnId, {
                force: true,
              })
                .catch((err) =>
                  setError(
                    err instanceof Error
                      ? err.message
                      : "Could not regenerate description."
                  )
                )
                .finally(() => setGenerating(false));
            }}
            className="flex-none cursor-pointer rounded-md border border-accent-purple/40 bg-accent-purple/10 px-2 py-1 text-[10px] font-semibold text-accent-purple transition-colors hover:bg-accent-purple/20 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {generating ? "AI…" : "Regenerate"}
          </button>
        </div>

        {error && (
          <p className="mb-3 text-[11px] text-red-400">{error}</p>
        )}

        <div className="overflow-x-auto rounded-[9px] border border-[#1d2740] bg-[#0b0f17] p-3.5">
          {generating && needsAi ? (
            <p className="font-mono text-[12px] text-[#5e6a85]">
              Generating JSON shape with AI…
            </p>
          ) : (
            <HighlightedJson source={liveShape.jsonSchema} />
          )}
        </div>

        <p className="mt-3 text-[10px] text-[#46506a]">
          Description and schema are generated automatically by AI.
        </p>
      </div>
    </aside>
  );
}
